// Static asset module declarations, mirroring next/image-types/global.
// `next-env.d.ts` — where Next normally loads these — is gitignored and
// regenerated by dev/build, so a fresh CI checkout type-checking without
// `.next` would fail every `import logo from "@/asset/flashwrench.png"`.
// This file is committed so bare `tsc --noEmit` resolves image imports
// on a clean clone. `skipLibCheck` keeps it from conflicting with the
// generated declarations when both are present.

type StaticImageAsset =
  import("next/dist/shared/lib/image-external").StaticImageData;

declare module "*.png" {
  const content: StaticImageAsset;
  export default content;
}

declare module "*.jpg" {
  const content: StaticImageAsset;
  export default content;
}

declare module "*.jpeg" {
  const content: StaticImageAsset;
  export default content;
}

declare module "*.gif" {
  const content: StaticImageAsset;
  export default content;
}

declare module "*.webp" {
  const content: StaticImageAsset;
  export default content;
}

declare module "*.avif" {
  const content: StaticImageAsset;
  export default content;
}

declare module "*.ico" {
  const content: StaticImageAsset;
  export default content;
}

declare module "*.bmp" {
  const content: StaticImageAsset;
  export default content;
}
